%TINTCOLORMAP Specifies the 5-level tint colour map - called by image_rm.m
function cbjet=tintColorMap()
 cbjet=[0,  0, 0.75; ...
        0,  0.75, 0.9; ...
        0.1,  1, 0.4; ...
        1,  1, 0; ...
        0.95, 0, 0]; %NB. This is comparable to tint
    
end



